name: mailru task

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build-storybook

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: out
          path: ./.out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: out
      - name: Upload to hotbox
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --endpoint-url https://hb.bizmrg.com --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: mailru_task
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: '.out'
